language: node_js
node_js:
  - "4"
before_install:
  - npm install -g gulp
  - npm install -g bower
  - npm install -g fayde-unify
install: npm install
before_script: gulp reset
script:
  - gulp version
  - gulp
  - gulp test